version: '3.7'

services:
  sfcastapiplatform_api_php_fpm:
    container_name: sfcastapiplatform-api-php-fpm
    build: docker/php-fpm
    ports:
      - "8900:9001"
    volumes:
      - .:/var/www/sfcastapiplatform
    depends_on:
      - sfcastapiplatform_api_db
    environment:
      PHP_IDE_CONFIG: serverName=sfcastapiplatform
      XDEBUG_CONFIG: remote_port=9999
      PHP_CS_FIXER_IGNORE_ENV: 1

  sfcastapiplatform_api_http:
    container_name: sfcastapiplatform-api-http
    image: nginx:1.19.1
    ports:
      - "8910:80"
    depends_on:
      - sfcastapiplatform_api_php_fpm
    volumes:
      - .:/var/www/sfcastapiplatform
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf

  sfcastapiplatform_api_db:
    container_name: sfcastapiplatform-api-db
    image: postgres:12
    ports:
      - "8920:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: sfcastapiplatform
      POSTGRES_DB: sfcastapiplatform
      POSTGRES_USER: sfcastapiplatform
